messages:
  no-permission: "&cYou do not have permission to do this."
  usage: "&e/spotlight send [player] [server]"
  console-player-required: "&cConsole must specify an online player carrier."
  player-offline: "&cPlayer is offline."
  cooldown: "&cYou can use spotlight again in {seconds}s."
  sent: "&aSpotlight request sent."
  reloaded: "&aSopSpotlight-Bukkit reloaded."

spotlight:
  server-id: ""
  default-cooldown-seconds: 300
  send-avatar: true
  sender-text: "%player_name%"
  lines:
    - " "
    - ""
    - ""
    - "<center-40><#08822A>{sender-text}</#08822A> <#0FFA51>is now playing on</#0FFA51></center>"
    - "<center-40><#F097F7>{server}</#F097F7></center>"
    - ""
    - "<center-24><hover:show_text:'<yellow>Click'><click:run_command:/server {server}><#B0DDBD>[<#0FFA51>Click here to join!<#B0DDBD>]</click></hover></center>"
    - ""
    - ""
    - " "
